#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
STOP=01

PROG="/etc/userdata/unified"

start_service() {
        PID=$(pgrep -f ${PROG} )
    procd_open_instance
    procd_set_param command /bin/bash "$PROG"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn ${threshold:-20} ${timeout:-5} ${retry:-3}
    procd_close_instance
}
stop_service() {
        echo "I am activated"
        pids=$( pgrep -f ${PROG} | xargs echo)
        for i in $pids; do extra_pids="${extra_pids} $(pgrep -P $i | xargs echo)"; done;
        kill $(echo "${extra_pids} ${pids}" ) 2> /dev/null
}